/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CadastroDAO;
import dto.CadastroDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Estante Virtual");
        
        tbListar.setSelectionBackground(new java.awt.Color(230, 204, 255)); 
        tbListar.setBackground(new java.awt.Color(255, 255, 255)); 
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        this.getContentPane().setBackground(java.awt.Color.WHITE);
         
    // Define o modelo da tabela "tbListar" com as novas colunas
    tbListar.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{
            "ID", "Tipo", "Nome", "Gênero", "Nota", "Favorito"
        }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column != 0; 
        }
    });

    tbListar.getModel().addTableModelListener(e -> {
        if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
            int row = e.getFirstRow();
            try {
                // Coleta os dados da linha que foi editada
                int id = Integer.parseInt(tbListar.getValueAt(row, 0).toString());
                String tipo = tbListar.getValueAt(row, 1).toString();
                String nome = tbListar.getValueAt(row, 2).toString();
                String genero = tbListar.getValueAt(row, 3).toString();
                int nota = Integer.parseInt(tbListar.getValueAt(row, 4).toString());

                // Converte o valor da coluna "Favorito" (que pode ser String ou Boolean)
                boolean favorito = Boolean.parseBoolean(tbListar.getValueAt(row, 5).toString());

                // Preenche o DTO com os novos dados
                CadastroDTO obj = new CadastroDTO();
                obj.setId(id);
                obj.setTipo(tipo);
                obj.setNome(nome);
                obj.setGenero(genero);
                obj.setNota(nota);
                obj.setFavorito(favorito);

                // Chama o DAO para salvar a alteração no banco
                CadastroDAO dao = new CadastroDAO();
                dao.alterarItem(obj); // Usa o método corrigido "alterarItem"

                JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");

                // Recarrega a lista 
                listarItens(); 

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Erro: O campo 'Nota' deve ser um número válido.");
                listarItens(); 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar alteração: " + ex.getMessage());
                listarItens(); 
            }
        }
    });

    // Carrega os dados iniciais na tabela (READ)
    listarItens();
    }
    
    // Método para contar e atualizar os números no topo
    public void atualizarContadores() {
        try {
            CadastroDAO dao = new CadastroDAO();
            // Busca a lista completa do banco para ter os números reais totais
            List<CadastroDTO> listaCompleta = dao.listarItens(""); 

            int contFilmes = 0;
            int contLivros = 0;
            int contJogos = 0;
            int contFavs = 0;

            for (CadastroDTO item : listaCompleta) {
                if (item.getTipo().equalsIgnoreCase("Filme")) {
                    contFilmes++;
                } else if (item.getTipo().equalsIgnoreCase("Livro")) {
                    contLivros++;
                } else if (item.getTipo().equalsIgnoreCase("Jogo")) {
                    contJogos++;
                }
                if (item.isFavorito()) {
                    contFavs++;
                }
            }

            // Atualiza as Labels na tela
            lblQtdFilmes.setText(String.valueOf(contFilmes));
            lblQtdLivros.setText(String.valueOf(contLivros));
            lblQtdJogos.setText(String.valueOf(contJogos));
            lblQtdFavs.setText(String.valueOf(contFavs));

        } catch (Exception e) {
            System.out.println("Erro ao atualizar contadores: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListar = new javax.swing.JTable();
        btnFiltrar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        chkFilme = new javax.swing.JCheckBox();
        chkLivro = new javax.swing.JCheckBox();
        chkJogo = new javax.swing.JCheckBox();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chkFavoritos = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQtdFilmes = new javax.swing.JLabel();
        lblQtdLivros = new javax.swing.JLabel();
        lblQtdFavs = new javax.swing.JLabel();
        lblQtdJogos = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        tbListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nome", "Gênero", "Avaliação", "Favorito"
            }
        ));
        tbListar.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbListar);

        jPanel1.add(jScrollPane1, "card2");

        btnFiltrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(204, 102, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnAdicionar.setBackground(new java.awt.Color(204, 153, 255));
        btnAdicionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("+ Adicionar item");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        chkFilme.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkFilme.setText("Filme");
        chkFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFilmeActionPerformed(evt);
            }
        });

        chkLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkLivro.setText("Livro");

        chkJogo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkJogo.setText("Jogo");

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/searchpng.png"))); // NOI18N
        jLabel1.setText("Buscar por (Nome):");

        chkFavoritos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkFavoritos.setText("Favoritos");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Filtrar por:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estante Virtual");

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(204, 102, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bookpng.png"))); // NOI18N
        jLabel5.setText("Livros");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/gamepng.png"))); // NOI18N
        jLabel6.setText("Jogos");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/moviepng.png"))); // NOI18N
        jLabel7.setText("Filmes");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/starpng.png"))); // NOI18N
        jLabel8.setText("Favs");

        lblQtdFilmes.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblQtdFilmes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdFilmes.setText("0");

        lblQtdLivros.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblQtdLivros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdLivros.setText("0");

        lblQtdFavs.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblQtdFavs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdFavs.setText("0");

        lblQtdJogos.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblQtdJogos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdJogos.setText("0");

        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(153, 0, 153));
        btnExcluir.setText("- Excluir item");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addGap(55, 55, 55)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(btnFiltrar)
                            .addGap(55, 55, 55)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(lblQtdFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(182, 182, 182)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblQtdLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(lblQtdJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblQtdFavs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(lblQtdFilmes)
                            .addComponent(lblQtdLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQtdJogos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQtdFavs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkJogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFavoritos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFilmeActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        filtrar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new CadastrarItem().setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        filtrar();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        listarItens();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirItemSelecionado();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JCheckBox chkFavoritos;
    private javax.swing.JCheckBox chkFilme;
    private javax.swing.JCheckBox chkJogo;
    private javax.swing.JCheckBox chkLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQtdFavs;
    private javax.swing.JLabel lblQtdFilmes;
    private javax.swing.JLabel lblQtdJogos;
    private javax.swing.JLabel lblQtdLivros;
    private javax.swing.JTable tbListar;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    // READ - lista todos os itens
    public void listarItens() {
        try {
            CadastroDAO dao = new CadastroDAO();
            List<CadastroDTO> lista = dao.listarItens(""); 
            DefaultTableModel model = (DefaultTableModel) tbListar.getModel();
            model.setRowCount(0); 

            for (CadastroDTO item : lista) {
                // Adiciona os dados na ordem correta 
                model.addRow(new Object[]{
                    item.getId(),       // Coluna 0 
                    item.getTipo(),     // Coluna 1
                    item.getNome(),     // Coluna 2
                    item.getGenero(),   // Coluna 3
                    item.getNota(),     // Coluna 4 
                    item.isFavorito()   // Coluna 5
                });
            }
            atualizarContadores();
            // Toda vez que a lista recarregar, os números lá em cima atualizam.
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar itens: " + e.getMessage());
        }
    }

    // READ + filtros
    public void filtrar() {
        try {
            CadastroDAO dao = new CadastroDAO();

            // 1. Busca no DAO usando o texto de pesquisa 
            List<CadastroDTO> lista = dao.listarItens(txtBuscar.getText());
            DefaultTableModel model = (DefaultTableModel) tbListar.getModel();
            model.setRowCount(0);
            boolean filtroTipoAtivo = chkFilme.isSelected() || chkLivro.isSelected() || chkJogo.isSelected();
            boolean filtroFavorito = chkFavoritos.isSelected();

            for (CadastroDTO item : lista) {
                boolean exibirPorTipo = false;
                boolean exibirPorFavorito = false;

                // 2. Lógica do filtro de Tipo (Filme, Livro, Jogo)
                if (!filtroTipoAtivo) {
                    // Se nenhum checkbox de tipo está marcado, mostra todos os tipos
                    exibirPorTipo = true; 
                } else {
                    if (chkFilme.isSelected() && item.getTipo().equalsIgnoreCase("Filme")) exibirPorTipo = true;
                    if (chkLivro.isSelected() && item.getTipo().equalsIgnoreCase("Livro")) exibirPorTipo = true;
                    if (chkJogo.isSelected() && item.getTipo().equalsIgnoreCase("Jogo")) exibirPorTipo = true;
                }

                // 3. Lógica do filtro de Favoritos
                if (!filtroFavorito) {
                    exibirPorFavorito = true; 
                } else {
                    if (item.isFavorito()) { 
                        exibirPorFavorito = true;
                    }
                }

                // 4. Só adiciona na tabela se passar nos DOIS filtros
                if (exibirPorTipo && exibirPorFavorito) {
                    model.addRow(new Object[]{
                        item.getId(),
                        item.getTipo(),
                        item.getNome(),
                        item.getGenero(),
                        item.getNota(),
                        item.isFavorito()
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao filtrar: " + e.getMessage());
        }
    }
    
    // DELETE - excluir algum item com o botao 
    private void excluirItemSelecionado() {
        int linhaSelecionada = tbListar.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, clique em um item da tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        try {
            // Pega o ID (coluna 0) e o Nome (coluna 2) para confirmar
            int id = Integer.parseInt(tbListar.getValueAt(linhaSelecionada, 0).toString());
            String nome = tbListar.getValueAt(linhaSelecionada, 2).toString();
            int confirmacao = JOptionPane.showConfirmDialog(this, 
                    "Tem certeza que deseja excluir o item:\n" + nome + "?", 
                    "Confirmar Exclusão", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmacao == JOptionPane.YES_OPTION) {
                // Chama o DAO para apagar do Banco de Dados
                CadastroDAO dao = new CadastroDAO();
                dao.excluirItem(id);
                JOptionPane.showMessageDialog(this, "Item excluído com sucesso!");

                listarItens(); 
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao tentar excluir: " + e.getMessage());
        }
    }
}
